# Generated by Django 4.2.3 on 2023-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('imei', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('alarm_code', models.CharField(choices=[('ACCOFF', 'Parada'), ('ACCON', 'Inicio'), ('OFFLINETIMEOUT', 'Tiempo de espera sin conexión'), ('STAYTIMEOUT', 'Tiempo de espera de estancia'), ('REMOVE', 'Desmontaje, sensor de luz, fallo de alimentación, enchufar y desenchufar'), ('LOWVOT', 'Baja electricidad'), ('ERYA', 'Segunda carga'), ('FENCEIN', 'Entrar en la cerca'), ('FENCEOUT', 'Fuera de la cerca'), ('SEP', 'Separado'), ('SOS', 'Alarma SOS'), ('OVERSPEED', 'Alarma de exceso de velocidad'), ('HOME', 'Residencia permanente anormal (casa)'), ('COMPANY', 'Residencia permanente anormal (empresa)'), ('CRASH', 'Alarma de colisión'), ('SHAKE', 'Vibración'), ('ACCELERATION', 'Aceleración rápida'), ('DECELERATION', 'Desaceleración rápida'), ('TURN', 'Giro brusco')], default='ACCOFF', max_length=20)),
                ('alarm_time', models.IntegerField()),
                ('device_type', models.IntegerField()),
                ('alarm_type', models.IntegerField()),
                ('position_type', models.CharField(blank=True, choices=[('GPS', 'GPS')], default='GPS', max_length=20, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('course', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('details', models.ManyToManyField(to='alarms.detail')),
            ],
        ),
    ]
