# Generated by Django 4.2.3 on 2023-09-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0005_vehiclestatus_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Alarma', 'verbose_name_plural': 'Alarmas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario del dispositivo', 'verbose_name_plural': 'Usuarios de los dispositivos'},
        ),
        migrations.AddField(
            model_name='user',
            name='imei',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VehicleStatus',
        ),
    ]
