# Generated by Django 4.2.3 on 2023-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0006_alter_detail_options_alter_user_options_user_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imei',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
