# Generated by Django 4.2.3 on 2023-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alter_user_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
